src/Entity/Artikel.php
<?php

namespace App\Entity;

use App\Repository\ArtikelRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtikelRepository::class)
 */
class Artikel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverFilename;

    /**
     * @ORM\Column(type="datetimetz")
     */
    private $created_on;

    /**
     * @ORM\Column(type="datetimetz")
     */
    private $update_on;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $harga;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $harga_d;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverFilename(): string
    {
        return $this->coverFilename;
    }

    public function setCoverFilename(string $coverFilename): self
    {
        $this->coverFilename = $coverFilename;

        return $this;
    }

    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->created_on;
    }

    public function setCreatedOn(\DateTimeInterface $created_on): self
    {
        $this->created_on = $created_on;
        // date_create();

        return $this;
    }

    public function getUpdateOn(): ?\DateTimeInterface
    {
        return $this->update_on;
    }

    // public function setUpdated()
    // {
    //     // WILL be saved in the database
    //     $this->updated = new \DateTime("now");
    // }

    public function setUpdateOn(\DateTimeInterface $update_on): self
    {
        // $this->update_on = $update_on;
        $this->update_on = new \DateTime("now");

        return $this;
    }

    public function getHarga(): ?string
    {
        return $this->harga;
    }

    public function setHarga(?string $harga): self
    {
        $this->harga = $harga;

        return $this;
    }

    public function getHargaD(): ?string
    {
        return $this->harga_d;
    }

    public function setHargaD(?string $harga_d): self
    {
        $this->harga_d = $harga_d;

        return $this;
    }
}

src/Form/ArtikelType.php
<?php

namespace App\Form;

use App\Entity\Artikel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;

 
class ArtikelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')            
            ->add('content', CKEditorType::class, [ 
                'label' => 'Deskripsi',                
                'config' => array(
                    'uiColor' => '#ffffff',
                    //...
                ),
            ])
            
            ->add('cover', FileType::class, [
                'label' => 'Cover (Image file, max 0.5 MB)',
                // unmapped means that this field is not associated to any entity property
                'mapped' => false,
                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => true,
                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '524k',
                        'mimeTypes' => [
                            'image/*',                            
                        ],
                        'mimeTypesMessage' => 'Please upload a valid Image File!',
                    ]),
                ],
            ])
            ->add('created_on', DateType::class, [
                // 'placeholder' => [
                //     'year' => 'Year', 'month' => 'Month', 'day' => 'Day',
                //     'hour' => 'Hour', 'minute' => 'Minute', 'second' => 'Second',
                // ],
                'widget' => 'single_text',
                // 'html5' => false,
                // 'input'  => 'datetime',
                
            ])
            ->add('update_on', DateType::class, [
                'widget' => 'choice',
                'input' => 'datetime',
            ])     
            ->add('harga', MoneyType::class, [
                'divisor' => 1,
                'grouping' => true,                
                'currency' => 'IDR',
                'scale' => 2,
                'help' => 'Tanpa menambahkan titik/koma',
            ])
            ->add('harga_d', MoneyType::class, [
                'divisor' => 1,
                'grouping' => true,                
                'currency' => 'IDR',
                'scale' => 2,
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Artikel::class,
        ]);
    }
}

src/Controller/ArtikelController.php
<?php

namespace App\Controller;

use App\Service\FileUploader;
use App\Entity\Artikel;
use App\Form\ArtikelType;
use App\Repository\ArtikelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/artikel")
 */
class ArtikelController extends AbstractController
{
    /**
     * @Route("/", name="artikel_index", methods={"GET"})
     */
    public function index(ArtikelRepository $artikelRepository): Response
    {
        return $this->render('artikel/index.html.twig', [
            'artikels' => $artikelRepository->findBy([], ['update_on' => 'DESC']),
        ]);
    }

    /**
     * @Route("/new", name="artikel_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $artikel = new Artikel();
        $form = $this->createForm(ArtikelType::class, $artikel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {            

            $coverFile = $form->get('cover')->getData();           
            if ($coverFile) {
                // $originalFilename = pathinfo($coverFile->getClientOriginalName(), PATHINFO_FILENAME);                
                // $safeFilename = $slugger->slug($originalFilename);
                $newFilename = md5(uniqid()).'.'.$coverFile->guessExtension();                
                try {
                    $coverFile->move(
                        $this->getParameter('cover_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $artikel->setCoverFilename($newFilename);
                // $coverFilename = $fileUploader->upload($coverFile);
                // $artikel->setCoverFilename($coverFilename);
            }   
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($artikel);
            $entityManager->flush();

            return $this->redirectToRoute('artikel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('artikel/new.html.twig', [
            'artikel' => $artikel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="artikel_show", methods={"GET"})
     */
    public function show(Artikel $artikel): Response
    {
        return $this->render('artikel/show.html.twig', [
            'artikel' => $artikel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="artikel_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Artikel $artikel): Response
    {
        $form = $this->createForm(ArtikelType::class, $artikel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $coverFile = $form->get('cover')->getData();
            $newFilename = md5(uniqid()).'.'.$coverFile->guessExtension();
            $coverFile->move(
                $this->getParameter('cover_directory'),
                $newFilename
            );
            $artikel->setCoverFilename($newFilename);

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('artikel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('artikel/edit.html.twig', [
            'artikel' => $artikel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="artikel_delete", methods={"POST"})
     */
    public function delete(Request $request, Artikel $artikel): Response
    {
        if ($this->isCsrfTokenValid('delete'.$artikel->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($artikel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('artikel_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/artikel/_delete_form.html.twig
<form method="post" action="{{ path('artikel_delete', {'id': artikel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artikel.id) }}">
		<button class="btn btn-sm btn-error btn-outline">Delete</button>
	</form>

templates/artikel/_form.html.twig
{{ form_start(form) }}
	<div class="flex flex-col">
		{{ form_errors(form, {'attr': {'class': 'alert alert-warning'}}) }} {{ form_row(form._token) }}
		<div class="mt-4">
			{{ form_label(form.title, 'Judul', {'label_attr': {'class': 'font-bold'}}) }} {{ form_widget(form.title, {'attr': {'class': 'form-control py-1 px-2 border border-gray-300', 'placeholder': 'Judul'}}) }}
		</div>
		<div class="mt-4">
			{{ form_label(form.content) }}
			{{ form_widget(form.content, {'attr': {'class': 'form-control py-1 px-2 border border-gray-300'}}) }}
		</div>
		<div class="mt-4">
			{{ form_label(form.cover) }}
			{{ form_widget(form.cover, {'attr': {'class': 'form-control py-1 px-2 border border-gray-300 text-xs'}}) }}
		</div>
		<div class="flex">
			<div class="mt-4 mr-4">
				{{ form_label(form.harga) }}
				{{ form_widget(form.harga, {'attr': {'class': 'form-control py-1 px-2 border border-gray-300', 'placeholder': '99.999'}}) }} {{ form_help(form.harga, {'attr': {'class': 'text-xs font-bold text-warning'}}) }}
			</div>
			<div class="mt-4">
				{{ form_label(form.harga_d, 'Harga Diskon') }}
				{{ form_widget(form.harga_d, {'attr': {'class': 'form-control py-1 px-2 border border-gray-300', 'placeholder': '49.999'}}) }}
			</div>
		</div>
		<div class="flex">
			<div class="mt-4 mr-4">
				{{ form_label(form.created_on, 'Diposting pada') }}
				{{ form_widget(form.created_on, {'attr': {'class': 'form-control py-1 px-2 border border-gray-300'}}) }}
			</div>
			<div class="mt-4">
				{{ form_label(form.update_on, 'Diupdate pada') }}
				{{ form_widget(form.update_on, {'attr': {'class': 'w-max py-1 px-2 border border-gray-300'}}) }}
			</div>
		</div>
		<button class="btn btn-sm btn-accent btn-outline w-max mt-4">{{ button_label|default('Save') }}</button>
	</div>
	{{ form_end(form) }}

templates/artikel/edit.html.twig
{% extends 'base.html.twig' %}

	{% block title %}Edit Artikel{% endblock %}

	{% block body %}
		<div class="bg-base p-7">
			<div class="flex justify-center items-center flex-col">
				<h1 class="text-xl font-bold">Form Edit Artikel</h1>
				{{ include('artikel/_form.html.twig', {'button_label': 'Update'}) }}
				{% if is_granted('ROLE_ADMIN') %}
					<div class="my-2">
						{{ include('artikel/_delete_form.html.twig') }}
					</div>
				{% endif %}
				<div class="">
					<a class="btn btn-sm btn-info btn-outline" href="{{ path('artikel_index') }}">back to list</a>
				</div>
			</div>
		</div>

	{% endblock %}

templates/artikel/index.html.twig
{% extends 'base.html.twig' %}

	{% block title %}Artikel index{% endblock %}

	{% block body %}
		<div class="m-4">
			<div class="flex items-center flex-col">
				<h1 class="m-2 py-2 font-bold text-accent uppercase">Artikel index</h1>
				<table class="table table-compact table-zebra w-full">
					<thead>
						<tr>
							<th>Id</th>
							<th>Judul</th>
							<th>Konten</th>
							<th>Harga</th>
							<th>Diskon</th>
							<th>Sampul</th>
							<th>Ditulis pada  [UTC+7:00]</th>
							<th>Diedit pada  [UTC+7:00]</th>
							<th>actions</th>
						</tr>
					</thead>
					<tbody>
						{% for artikel in artikels %}
							<tr class="hover">
								<td>{{ artikel.id }}</td>
								<td>{{ artikel.title }}</td>
								<td>{{ artikel.content|u.truncate(50, '...') }}</td>
								<td>{{ artikel.harga|format_currency('IDR') }}</td>
								<td>{{ artikel.hargaD|format_currency('IDR') }}</td>
								<td>{{ artikel.coverFilename|u.truncate(15, '...') }}</td>
								<td>{{ artikel.createdOn ? artikel.createdOn|date('F jS, Y', 'Asia/Bangkok') : '' }}</td>
								<td>{{ artikel.updateOn ? artikel.updateOn|date('F jS, Y \\a\\t g:i a', 'Asia/Bangkok') : '' }}</td>
								<td class="flex flex-row">
									<a class="btn btn-xs btn-link link-accent link-hover -ml-3" href="{{ path('artikel_show', {'id': artikel.id}) }}">show</a>
									<a class="btn btn-xs btn-link link-accent link-hover" href="{{ path('artikel_edit', {'id': artikel.id}) }}">edit</a>
								</td>
							</tr>
						{% else %}
							<tr>
								<td colspan="6">no records found</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="mx-8">
				<a class="mt-4 btn btn-sm btn-accent btn-outline" href="{{ path('artikel_new') }}">Create new</a>
			</div>
		</div>
	{% endblock %}

templates/artikel/new.html.twig
{% extends 'base.html.twig' %}

	{% block title %}New Artikel{% endblock %}

	{% block body %}
		<div class="bg-base p-7">
			<div class="flex justify-center items-center flex-col">
				<h1 class="text-xl font-bold">Form Artikel Baru</h1>
				{{ include('artikel/_form.html.twig') }}
				<div class="">
					<a class="btn btn-sm btn-info btn-outline" href="{{ path('artikel_index') }}">back to list</a>
				</div>
			</div>
		</div>
	{% endblock %}

templates/artikel/show.html.twig
{% extends 'base.html.twig' %}

	{% block title %}Artikel{% endblock %}

	{% block body %}
		<div class="m-8 p-4">
			<h1>Artikel</h1>
			<div class="m-5">
				<div class="w-60 h-48 bg-center bg-gray-300 bg-cover bg-current bg-opacity-40" style="background-image: url('{{ asset('uploads/covers/' ~ artikel.coverFilename) }}'); background-blend-mode: multiply"></div>
			</div>
			<table class="table">
				<tbody>
					<tr>
						<th>Id</th>
						<td>{{ artikel.id }}</td>
					</tr>
					<tr>
						<th>Title</th>
						<td>{{ artikel.title }}</td>
					</tr>
					<tr>
						<th>Content</th>
						<td>{{ artikel.content }}</td>
					</tr>
					<tr>
						<th>Harga</th>
						<td>{{ artikel.harga }}</td>
					</tr>
					<tr>
						<th>Diskon</th>
						<td>{{ artikel.hargaD }}</td>
					</tr>
					<tr>
						<th>Created_on</th>
						<td>{{ artikel.createdOn ? artikel.createdOn|date('Y-m-d H:i:s T') : '' }}</td>
					</tr>
					<tr>
						<th>Update_on</th>
						<td>{{ artikel.updateOn ? artikel.updateOn|date('Y-m-d H:i:s T') : '' }}</td>
					</tr>
				</tbody>
			</table>

			<a class="btn btn-sm btn-info btn-outline" href="{{ path('artikel_index') }}">back to list</a>

			<a class="btn btn-sm btn-outline btn-warning" href="{{ path('artikel_edit', {'id': artikel.id}) }}">edit</a>

			{% if is_granted('ROLE_ADMIN') %}
				<div class="my-2">
					{{ include('artikel/_delete_form.html.twig') }}
				</div>
			{% endif %}
		</div>
	{% endblock %}